---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cityapp-secretless
  namespace: cityapp
---
apiVersion: v1
kind: Service
metadata:
  name: cityapp-secretless
  namespace: cityapp
  labels:
    app: cityapp-secretless
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: cityapp-secretless
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cityapp-secretless
  name: cityapp-secretless
  namespace: cityapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cityapp-secretless
  template:
    metadata:
      labels:
        app: cityapp-secretless
    spec:
      serviceAccountName: cityapp-secretless
      containers:
      - image:  409556437035.dkr.ecr.ap-southeast-1.amazonaws.com/ivanlee/cityapp:1.0
        imagePullPolicy: IfNotPresent
        name: cityapp
        env:
          - name: DBAddress
            value: "127.0.0.1"
          - name: DBPort
            value: "3306"
          - name: DBName
            value: "world"
          - name: DBPassword
            value: ""
          - name: DBUsername
            value: ""
        ports:
        - containerPort: 3000
          name: http
      - image: cyberark/secretless-broker:latest
        imagePullPolicy: IfNotPresent
        name: authenticator
        args: ["-f", "/etc/secretless/secretless.yaml"]
        ports:
        - containerPort: 3306
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_APPLIANCE_URL
            value: "https://follower.dap.svc.cluster.local/api"
          - name: CONJUR_AUTHN_URL
            value: "https://follower.dap.svc.cluster.local/api/authn-k8s/okd"
          - name: CONJUR_ACCOUNT
            value: "cyberark"
          - name: CONJUR_AUTHN_LOGIN
            value: "host/conjur/authn-k8s/okd/apps/cityapp/service_account/cityapp-secretless"
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: follower-certificate
                key: ssl-certificate
        volumeMounts:
          - mountPath: /etc/secretless
            name: config
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: cityapp-secretless-config
### This is not required for integrated registry
#      imagePullSecrets:
#       - name: dockerpullsecret
