---
apiVersion: v1
kind: Service
metadata:
  name: follower
  labels:
    app: follower
spec:
  ports:
  - port: 443
    name: https
  - port: 636
    name: ldaps
  selector:
    app: follower
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: follower
spec:
  replicas: 1
#
  selector:
    matchLabels:
      app: follower
#
  template:
    metadata:
      labels:
        app: follower
        name: follower
        role: follower
    spec:
      serviceAccountName: conjur-cluster
      volumes:
      - name: seedfile
        emptyDir:
          medium: Memory
      - name: conjur-token
        emptyDir:
          medium: Memory
      initContainers:
#      Containers:
      - name: authenticator
        image: 409556437035.dkr.ecr.ap-southeast-1.amazonaws.com/ivanlee/dap-seedfetcher:0.1.5
        imagePullPolicy: Always
        env:
          - name: CONJUR_SEED_FILE_URL
            value: https://master-dap.cyberarkdemo.com/configuration/cyberark/seed/follower
          - name: SEEDFILE_DIR
            value: /tmp/seedfile
          - name: FOLLOWER_HOSTNAME
            value: follower   # this should match the service name
          - name: AUTHENTICATOR_ID
            value: okd
          - name: CONJUR_ACCOUNT
            value: cyberark

          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: master-certificate
                key: ssl-certificate

          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_AUTHN_LOGIN
            value: host/conjur/authn-k8s/okd/apps/dap/service_account/conjur-cluster
        volumeMounts:
          - name: seedfile
            mountPath: /tmp/seedfile
          - name: conjur-token
            mountPath: /run/conjur

      containers:
      - name: dap-appliance
        command: ["/tmp/seedfile/start-follower.sh"]
        image: 409556437035.dkr.ecr.ap-southeast-1.amazonaws.com/ivanlee/conjur-appliance:12.0.0
        imagePullPolicy: IfNotPresent
        env:
          - name: CONJUR_AUTHENTICATORS
            value: authn-k8s/okd
          - name: SEEDFILE_DIR
            value: /tmp/seedfile
        ports:
        - containerPort: 443
          name: https
        - containerPort: 636
          name: ldaps
        - containerPort: 5432
          name: pg-main
        - containerPort: 5433
          name: pg-audit
        readinessProbe:
          httpGet:
            path: /health
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
          - name: seedfile
            mountPath: /tmp/seedfile
            readOnly: true
# Not required when using internal registry
#      imagePullSecrets:
#        - name: dockerpullsecret
